# Service to return commanded velocity from desired velocity
geometry_msgs/Point pos
geometry_msgs/Point vel
geometry_msgs/Point velDes
float32 dt
geometry_msgs/Point[] inRangePos
geometry_msgs/Point[] inRangeVel
---
geometry_msgs/Point velCommand
